// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBizdjkLcHX3N3FcuUeoEOKcJKub-QPVyI',
    appId: '1:912144247401:web:e9ad2d9aad3790f973d0f8',
    messagingSenderId: '912144247401',
    projectId: 'crudapp-8c2f9',
    authDomain: 'crudapp-8c2f9.firebaseapp.com',
    storageBucket: 'crudapp-8c2f9.firebasestorage.app',
    measurementId: 'G-58B3943XH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi2Z9gb5nK-v4_FKijZImz9gBBOVA5saw',
    appId: '1:912144247401:android:c598c66f8fc8106a73d0f8',
    messagingSenderId: '912144247401',
    projectId: 'crudapp-8c2f9',
    storageBucket: 'crudapp-8c2f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhmEiriGMziXhNvI9FejiDnwCbmwX7Lxs',
    appId: '1:912144247401:ios:2ec6f511493519cc73d0f8',
    messagingSenderId: '912144247401',
    projectId: 'crudapp-8c2f9',
    storageBucket: 'crudapp-8c2f9.firebasestorage.app',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhmEiriGMziXhNvI9FejiDnwCbmwX7Lxs',
    appId: '1:912144247401:ios:2ec6f511493519cc73d0f8',
    messagingSenderId: '912144247401',
    projectId: 'crudapp-8c2f9',
    storageBucket: 'crudapp-8c2f9.firebasestorage.app',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBizdjkLcHX3N3FcuUeoEOKcJKub-QPVyI',
    appId: '1:912144247401:web:0b68fd569b16a8d373d0f8',
    messagingSenderId: '912144247401',
    projectId: 'crudapp-8c2f9',
    authDomain: 'crudapp-8c2f9.firebaseapp.com',
    storageBucket: 'crudapp-8c2f9.firebasestorage.app',
    measurementId: 'G-YSD7R6Q02Q',
  );
}
