// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLBlrlTjTlRWCHjTL9Vx2OMipCG1f189o',
    appId: '1:547790198939:web:215670b3c2c83216940e3e',
    messagingSenderId: '547790198939',
    projectId: 'guia7-19de4',
    authDomain: 'guia7-19de4.firebaseapp.com',
    storageBucket: 'guia7-19de4.firebasestorage.app',
    measurementId: 'G-K0R9KR35CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBibyPCtzXc1q9ycAiLp4X1FOdQbOqNWFQ',
    appId: '1:547790198939:android:fd4c1a9d8280aa88940e3e',
    messagingSenderId: '547790198939',
    projectId: 'guia7-19de4',
    storageBucket: 'guia7-19de4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg2t4hEBTJ4JealvVv83OgpmUQhrL3jQY',
    appId: '1:547790198939:ios:93e917095c3e5dc9940e3e',
    messagingSenderId: '547790198939',
    projectId: 'guia7-19de4',
    storageBucket: 'guia7-19de4.firebasestorage.app',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg2t4hEBTJ4JealvVv83OgpmUQhrL3jQY',
    appId: '1:547790198939:ios:93e917095c3e5dc9940e3e',
    messagingSenderId: '547790198939',
    projectId: 'guia7-19de4',
    storageBucket: 'guia7-19de4.firebasestorage.app',
    iosBundleId: 'com.example.firebasecrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLBlrlTjTlRWCHjTL9Vx2OMipCG1f189o',
    appId: '1:547790198939:web:f2a1d28cd6365ddb940e3e',
    messagingSenderId: '547790198939',
    projectId: 'guia7-19de4',
    authDomain: 'guia7-19de4.firebaseapp.com',
    storageBucket: 'guia7-19de4.firebasestorage.app',
    measurementId: 'G-HJHN284C1S',
  );

}